// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bind_by_rowid_cpp
SEXP bind_by_rowid_cpp(SEXP x_dt, SEXP y_dt, const IntegerVector& x_idx, const IntegerVector& y_idx, const CharacterVector& overlap);
RcppExport SEXP _fuzzystring_bind_by_rowid_cpp(SEXP x_dtSEXP, SEXP y_dtSEXP, SEXP x_idxSEXP, SEXP y_idxSEXP, SEXP overlapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type x_dt(x_dtSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y_dt(y_dtSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type x_idx(x_idxSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type y_idx(y_idxSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type overlap(overlapSEXP);
    rcpp_result_gen = Rcpp::wrap(bind_by_rowid_cpp(x_dt, y_dt, x_idx, y_idx, overlap));
    return rcpp_result_gen;
END_RCPP
}
// bind_by_rowid_cpp_matches
SEXP bind_by_rowid_cpp_matches(SEXP x_dt, SEXP y_dt, SEXP matches_dt, const CharacterVector& overlap);
RcppExport SEXP _fuzzystring_bind_by_rowid_cpp_matches(SEXP x_dtSEXP, SEXP y_dtSEXP, SEXP matches_dtSEXP, SEXP overlapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type x_dt(x_dtSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y_dt(y_dtSEXP);
    Rcpp::traits::input_parameter< SEXP >::type matches_dt(matches_dtSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type overlap(overlapSEXP);
    rcpp_result_gen = Rcpp::wrap(bind_by_rowid_cpp_matches(x_dt, y_dt, matches_dt, overlap));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fuzzystring_bind_by_rowid_cpp", (DL_FUNC) &_fuzzystring_bind_by_rowid_cpp, 5},
    {"_fuzzystring_bind_by_rowid_cpp_matches", (DL_FUNC) &_fuzzystring_bind_by_rowid_cpp_matches, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_fuzzystring(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
